### ISSUE TITLE
Panning zoomed image instead of original

### ISSUE THREAD

**Issue by ynechaev** [zeknoss/vue-magnifier#4]
I noticed something strange while looking at your component. Not sure if it's intentional or not, but it feels like mouse position is taken from **zoomed** image coordinates rather than **original** one. 
Basically it means when you want to hover on a part of image it becomes confusing since it's a bit off and you need to readjust.

**Comment by zeknoss** [comment]
Hey @ynechaev,
Thank you for the feedback. This component was originally created for a project of mine and the designer has a very strict guideline about the UX, so yeah. It is intentional :)
If you think the behavior could be improved, you can always create a PR with your changes and we can take a look and even merge it.

Best
